"""No Auto-Greet's FOMOD installer, written into a release folder (nexus-tools/docs/FOMOD-STANDARD.md, the owner's
house standard of 2026-10-01). Shape and checks from fo4-silhouette tools/fomod_pack.py.

    python tools/fomod_pack.py <release folder> <version> [--draft]

Writes <release folder>/fomod/: ModuleConfig.xml, info.xml, images/*.png and screenshot.png.
- The install is REFUSED below game 1.10.163 (rule 2); No Auto-Greet has no plugin at all. F4SE and Runtime
  Database are named on the first page (rule 4a); without them the dll does nothing and its log says why.
- Every top-level entry of the release folder is installed as it is, read from the folder.
- Pages: "Checking your setup" (ONE Required option holding the whole checklist), then one page per feature, its
  card and text shown without a click (rule 4: one Required option alone in the step's first group).
- Cards: Publisher-bud's renders, D:/F4Output/cards/docs/img/<card> (the page card, fc60cbe), resized to 1000 px.
  --draft builds without them (no images) to check everything else; a release never uses it.
Validates ModuleConfig.xml against the 5.0 schema and checks every image and source it names exists.
"""
import html
import pathlib
import sys

from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parent.parent
XSD = ROOT.parent / 'fo4-silhouette' / 'tools' / 'fomod' / 'ModuleConfig5.0.xsd'   # the schema Vortex validates with
CARDS = ROOT / 'docs' / 'img'
SCHEMA = 'http://qconsulting.ca/fo3/ModConfig5.0.xsd'   # exactly: Vortex reads the version out of this text
NAME = 'No Auto-Greet'

# (step name, card file, plain-text description). Facts as README.md has them.
FEATURES = [
    ('Traders wait until you talk to them', 'card.jpg',
     'In the vanilla game a trader opens a conversation, camera and all, the moment you come within about 2.5 m, and '
     'calls out a hello as you pass their stall. With No Auto-Greet traders wait until you press Talk.\n'
     'A trader is anyone in a faction with a merchant container: shopkeepers, doctors, traveling merchants, '
     'settlement shopkeepers and other mods\' traders. Anyone who is or has been your companion is left alone, and '
     'everyone else behaves exactly as in the vanilla game: companions, quest NPCs, settlers, guards.'),
]
EXTRAS = ('One file, any game version',
          'One F4SE plugin for Fallout 4 1.10.163 and the Anniversary Edition 1.11.x, through Runtime Database. No '
          'plugin file, no scripts, no load-order slot: safe to add or remove mid-game.\n'
          'Documents/My Games/Fallout4/F4SE/NoAutoGreet.log says whether it hooked and how many trader factions it found.')
SETUP = ('Your setup',
         'F4SE: check this yourself -- runs the plugin (f4se.silverlock.org).\n'
         'Runtime Database: check this yourself -- finds the game\'s functions on 1.10.163 and Anniversary '
         '(Nexus 108394).\n'
         'Without either, No Auto-Greet does nothing and NoAutoGreet.log says why.')


def esc(text):
    return html.escape(text, quote=True)


def option(name, description, image=None, flag='shown'):
    picture = f'\n              <image path="fomod\\images\\{image}"/>' if image else ''
    return f'''            <plugin name="{esc(name)}">
              <description>{esc(description)}</description>{picture}
              <conditionFlags><flag name="{flag}">1</flag></conditionFlags>
              <typeDescriptor><type name="Required"/></typeDescriptor>
            </plugin>'''


def page(step, group, opt):
    return f'''    <installStep name="{esc(step)}">
      <optionalFileGroups order="Explicit">
        <group name="{esc(group)}" type="SelectAll">
          <plugins order="Explicit">
{opt}
          </plugins>
        </group>
      </optionalFileGroups>
    </installStep>'''


def module_config(entries, images):
    installs = []
    for e in entries:
        kind = 'folder' if e.is_dir() else 'file'
        installs.append(f'    <{kind} source="{esc(e.name)}" destination="{esc(e.name)}" priority="0"/>')
    pages = [page('Checking your setup', 'Requirements', option(SETUP[0], SETUP[1], flag='setup'))]
    pages += [page(n, n, option(n, d, img if images else None)) for n, img, d in FEATURES]
    pages.append(page(EXTRAS[0], EXTRAS[0], option(EXTRAS[0], EXTRAS[1])))
    module_image = f'\n  <moduleImage path="fomod\\images\\{FEATURES[0][1]}"/>' if images else ''
    return f'''<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by tools/fomod_pack.py (nexus-tools/docs/FOMOD-STANDARD.md). Edit the tool, not this file. -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="{SCHEMA}">
  <moduleName>{esc(NAME)}</moduleName>{module_image}
  <moduleDependencies operator="And">
    <gameDependency version="1.10.163.0"/>
  </moduleDependencies>
  <requiredInstallFiles>
{chr(10).join(installs)}
  </requiredInstallFiles>
  <installSteps order="Explicit">
{chr(10).join(pages)}
  </installSteps>
</config>
'''


def main():
    args = [a for a in sys.argv[1:] if not a.startswith('--')]
    draft = '--draft' in sys.argv
    if len(args) != 2:
        sys.exit(__doc__)
    out, version = pathlib.Path(args[0]), args[1]
    entries = sorted((e for e in out.iterdir() if e.name.lower() != 'fomod'), key=lambda e: e.name.lower())
    if not entries:
        sys.exit(f'{out} holds nothing to install')
    fomod = out / 'fomod'
    (fomod / 'images').mkdir(parents=True, exist_ok=True)
    images = not draft
    if images:
        for _n, card, _d in FEATURES:
            src = CARDS / card
            if not src.exists():
                sys.exit(f'no card {src} -- Publisher-bud renders them; --draft builds without')
            pic = Image.open(src).convert('RGB')
            pic.resize((1000, round(1000 * pic.height / pic.width)), Image.LANCZOS).save(fomod / 'images' / card, quality=88)
        first = Image.open(fomod / 'images' / FEATURES[0][1])
        first.convert('RGB').save(fomod / 'screenshot.png')   # MO2 shows this, not moduleImage
    (fomod / 'ModuleConfig.xml').write_text(module_config(entries, images), encoding='utf-8-sig')
    (fomod / 'info.xml').write_text(f'''<?xml version="1.0" encoding="UTF-8"?>
<fomod>
  <Name>{esc(NAME)}</Name>
  <Author>Dudu'sButt</Author>
  <Version>{esc(version)}</Version>
  <Website>https://github.com/ReidenXerx/fo4-no-auto-greet</Website>
  <Description>Traders stop opening a conversation, or calling out to you, when you walk past.</Description>
</fomod>
''', encoding='utf-8-sig')

    from lxml import etree
    schema = etree.XMLSchema(etree.parse(str(XSD)))
    doc = etree.parse(str(fomod / 'ModuleConfig.xml'))
    if not schema.validate(doc):
        sys.exit('ModuleConfig.xml fails the 5.0 schema:\n' + '\n'.join(str(e) for e in schema.error_log))
    for el in doc.iter('image', 'moduleImage'):
        if not (out / el.get('path').replace('\\', '/')).exists():
            sys.exit(f'the installer shows {el.get("path")}, which is not in the release')
    for el in doc.iter('file', 'folder'):
        if not (out / el.get('source')).exists():
            sys.exit(f'the installer installs {el.get("source")}, which is not in the release')
    print(f'fomod: {len(entries)} entries installed as they are, the setup page, {len(FEATURES)} feature pages + the '
          f'rest{" (DRAFT: no cards)" if draft else ""}; valid against {XSD.name}')


if __name__ == '__main__':
    main()
